app = "pranking-backend"
primary_region = "fra"  # можно "waw" для Польши (ближе к Украине)

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  auto_start_machines = true
  auto_stop_machines = true

  [[services.ports]]
    port = 80
